language: python
python:
 - "2.6"
 - "2.7"
# Someday, soon.
# - "3.2"
install: ./.travis-dev-setup.sh
script: ./.travis-run-tests.sh
notifications:
    email: false
    irc:
        - "irc.freenode.net#moksha"
    on_success: change
    on_failure: change
